from pathlib import Path

from app.domain.experience import CatalogGarment


def garment(
    garment_id: str,
    name: str,
    category: str,
    tone: str,
    audience: str,
    body_types: list[str],
    occasions: list[str],
    tags: list[str],
    material: str,
    silhouette: str,
) -> CatalogGarment:
    return CatalogGarment(
        id=garment_id,
        product_id=f"preset-{garment_id}",
        name=name,
        category=category,
        tone=tone,
        sizes=["S", "M", "L", "XL"],
        image_url=f"/api/v1/catalog/garments/{garment_id}/image",
        audience=audience,
        body_types=body_types,
        occasions=occasions,
        tags=tags,
        material=material,
        silhouette=silhouette,
    )


GARMENTS = [
    garment(
        "w-wrap-ivory",
        "象牙白系带衬衫",
        "top",
        "ivory",
        "women",
        ["triangle", "rectangle", "hourglass"],
        ["work", "date", "city"],
        ["v-neck", "waist-defined", "soft"],
        "viscose",
        "wrap",
    ),
    garment(
        "w-cardigan-sage",
        "鼠尾草短款开衫",
        "top",
        "sage",
        "women",
        ["rectangle", "petite", "hourglass"],
        ["cafe", "date", "daily"],
        ["cropped", "layering", "soft"],
        "cotton-knit",
        "cropped",
    ),
    garment(
        "w-linen-coral",
        "珊瑚色亚麻衬衫",
        "top",
        "coral",
        "women",
        ["triangle", "oval", "rectangle"],
        ["beach", "travel", "daily"],
        ["breathable", "relaxed", "sunny"],
        "linen",
        "relaxed",
    ),
    garment(
        "w-knit-navy",
        "海军蓝修身针织衫",
        "top",
        "navy",
        "women",
        ["hourglass", "rectangle"],
        ["work", "city", "date"],
        ["fitted", "minimal", "short-sleeve"],
        "rib-knit",
        "fitted",
    ),
    garment(
        "w-trousers-sand",
        "沙色高腰阔腿裤",
        "bottom",
        "sand",
        "women",
        ["triangle", "rectangle", "tall"],
        ["work", "travel", "city"],
        ["high-waist", "wide-leg", "fluid"],
        "linen-blend",
        "wide-leg",
    ),
    garment(
        "w-jeans-indigo",
        "深靛直筒牛仔裤",
        "bottom",
        "indigo",
        "women",
        ["triangle", "rectangle", "hourglass"],
        ["daily", "city", "travel"],
        ["straight", "denim", "classic"],
        "denim",
        "straight",
    ),
    garment(
        "w-dress-shirt-blue",
        "雾蓝衬衫式中长裙",
        "dress",
        "mist-blue",
        "women",
        ["triangle", "oval", "rectangle", "hourglass"],
        ["work", "travel", "date"],
        ["waist-defined", "midi", "versatile"],
        "cotton-poplin",
        "a-line",
    ),
    garment(
        "w-dress-slip-black",
        "黑色极简吊带裙",
        "dress",
        "black",
        "women",
        ["hourglass", "rectangle"],
        ["date", "evening", "beach"],
        ["minimal", "layering", "fluid"],
        "satin",
        "column",
    ),
    garment(
        "m-oxford-sky",
        "天蓝牛津纺衬衫",
        "top",
        "sky-blue",
        "men",
        ["rectangle", "inverted-triangle", "oval"],
        ["work", "city", "date"],
        ["classic", "clean", "layering"],
        "cotton-oxford",
        "regular",
    ),
    garment(
        "m-overshirt-charcoal",
        "炭灰宽松工装衬衫",
        "outerwear",
        "charcoal",
        "men",
        ["rectangle", "slim", "oval"],
        ["city", "travel", "daily"],
        ["layering", "relaxed", "utility"],
        "brushed-cotton",
        "relaxed",
    ),
    garment(
        "m-polo-cream",
        "奶油色肌理针织 Polo",
        "top",
        "cream",
        "men",
        ["rectangle", "inverted-triangle"],
        ["date", "cafe", "city"],
        ["textured", "smart-casual", "breathable"],
        "cotton-knit",
        "regular",
    ),
    garment(
        "m-bomber-olive",
        "橄榄绿轻量飞行夹克",
        "outerwear",
        "olive",
        "men",
        ["rectangle", "slim", "tall"],
        ["travel", "city", "daily"],
        ["sporty", "layering", "lightweight"],
        "nylon",
        "regular",
    ),
    garment(
        "m-trousers-charcoal",
        "炭灰锥形西裤",
        "bottom",
        "charcoal",
        "men",
        ["rectangle", "inverted-triangle", "tall"],
        ["work", "city", "date"],
        ["tapered", "clean", "smart"],
        "wool-blend",
        "tapered",
    ),
    garment(
        "m-jeans-blue",
        "中蓝直筒牛仔裤",
        "bottom",
        "blue",
        "men",
        ["rectangle", "inverted-triangle", "oval"],
        ["daily", "travel", "city"],
        ["straight", "classic", "denim"],
        "denim",
        "straight",
    ),
    garment(
        "m-blazer-camel",
        "驼色单排扣西装",
        "outerwear",
        "camel",
        "men",
        ["rectangle", "slim", "oval"],
        ["work", "date", "city"],
        ["structured", "smart", "layering"],
        "wool-blend",
        "tailored",
    ),
    garment(
        "m-field-navy",
        "深海军蓝机能夹克",
        "outerwear",
        "navy",
        "men",
        ["rectangle", "inverted-triangle", "oval"],
        ["travel", "outdoor", "city"],
        ["weatherproof", "utility", "layering"],
        "technical-nylon",
        "regular",
    ),
    garment(
        "knit-sand",
        "米色针织上衣",
        "top",
        "sand",
        "unisex",
        ["rectangle", "triangle", "oval"],
        ["daily", "cafe"],
        ["soft", "minimal"],
        "cotton-knit",
        "relaxed",
    ),
    garment(
        "denim-blue",
        "深蓝牛仔夹克",
        "outerwear",
        "blue",
        "unisex",
        ["rectangle", "slim", "triangle"],
        ["daily", "travel", "city"],
        ["denim", "layering"],
        "denim",
        "regular",
    ),
    garment(
        "coat-brown",
        "棕色短外套",
        "outerwear",
        "brown",
        "unisex",
        ["rectangle", "triangle", "oval"],
        ["city", "work", "travel"],
        ["short", "structured"],
        "wool-blend",
        "boxy",
    ),
]


def get_garment(garment_id: str) -> CatalogGarment | None:
    return next((item for item in GARMENTS if item.id == garment_id), None)


def get_catalog_garment_path(garment_id: str) -> Path | None:
    garment_item = get_garment(garment_id)
    if garment_item is None:
        return None
    target = Path(__file__).parent / "assets" / "garments" / f"{garment_item.id}.webp"
    return target if target.is_file() else None
